### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by timominous** [tannernelson/csqlite#2]
You should create a new release/tag since the old import path for `CSQLiteMac` is still the one being used.

**Comment by tanner0101** [comment]
Good catch. Will do that when back on a computer.

**Comment by tanner0101** [comment]
Done.

**Comment by timominous** [comment]
Awesome! Thanks @tannernelson

**Comment by timominous** [comment]
@tannernelson It's not released yet.

**Comment by tanner0101** [comment]
I force updated the `0.1.0` tag. Did it not work?

**Comment by timominous** [comment]
Ah I see. Needed to clear old packages.

**Comment by tanner0101** [comment]
I'm basically always running `rm -rf Packages && rm -rf .build && swift build` to avoid SPM bugs.
